# Generated by Django 5.2.16 on 2026-07-15 08:02

import apps.accounts.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('university', models.TextField(blank=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('avatar_url', models.TextField(blank=True)),
                ('portfolio_url', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('oauth_provider', models.CharField(blank=True, choices=[('github', 'GitHub')], max_length=20, null=True)),
                ('oauth_subject', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=20)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_platform_admin', models.BooleanField(default=False)),
                ('token_version', models.IntegerField(default=0)),
                ('failed_login_count', models.SmallIntegerField(default=0)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', apps.accounts.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('verified_student', 'Verified Student'), ('hackathon_veteran', 'Hackathon Veteran')], max_length=30)),
                ('awarded_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('sponsor', 'Sponsor'), ('judge', 'Judge'), ('mentor', 'Mentor')], max_length=20)),
                ('scope_type', models.CharField(choices=[('organization', 'Organization'), ('hackathon', 'Hackathon'), ('track', 'Track')], max_length=20)),
                ('scope_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(condition=models.Q(('lock_until__isnull', False)), fields=['lock_until'], name='account_lock_until_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('oauth_provider__isnull', False)), fields=('oauth_provider', 'oauth_subject'), name='unique_oauth_identity'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['user'], name='accounts_ba_user_id_479ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['scope_type', 'scope_id'], name='accounts_ro_scope_t_913d45_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'scope_type', 'scope_id'), name='unique_role_assignment'),
        ),
    ]
