# Generated by Django 5.2.16 on 2026-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='oauth_provider',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('google', 'Google')], max_length=20, null=True),
        ),
    ]
