# Generated by Django 5.2.16 on 2026-07-22 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0001_initial'),
        ('submissions', '0002_submissiontrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgingRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('open', 'Open'), ('closed', 'Closed')], default='not_started', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_rounds', to='hackathons.hackathon')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judging_rounds', to='hackathons.challengetrack')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='judging.judginground')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField()),
                ('judge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_assignments', to=settings.AUTH_USER_MODEL)),
                ('reassigned_from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_judging_assignments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_assignments', to='submissions.submission')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='judging.judginground')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='sent', max_length=10)),
                ('invited_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='judging.judginground')),
            ],
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='judging.judginground')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_value', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='final', max_length=10)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, default='')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.judgingcriterion')),
                ('judge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='submissions.submission')),
            ],
        ),
        migrations.AddIndex(
            model_name='judginground',
            index=models.Index(fields=['hackathon'], name='judging_jud_hackath_d89c64_idx'),
        ),
        migrations.AddConstraint(
            model_name='judginground',
            constraint=models.UniqueConstraint(fields=('hackathon', 'track'), name='unique_judging_round_per_hackathon_track'),
        ),
        migrations.AddConstraint(
            model_name='judginground',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', True)), fields=('hackathon',), name='unique_overall_judging_round_per_hackathon'),
        ),
        migrations.AddIndex(
            model_name='judgingcriterion',
            index=models.Index(fields=['round'], name='judging_jud_round_i_86bf15_idx'),
        ),
        migrations.AddConstraint(
            model_name='judgingcriterion',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', models.F('min_score'))), name='criterion_max_gt_min'),
        ),
        migrations.AddConstraint(
            model_name='judgingcriterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 100)), name='criterion_weight_0_to_100'),
        ),
        migrations.AddIndex(
            model_name='judgingassignment',
            index=models.Index(fields=['judge_user'], name='judging_jud_judge_u_412912_idx'),
        ),
        migrations.AddConstraint(
            model_name='judgingassignment',
            constraint=models.UniqueConstraint(fields=('round', 'submission', 'judge_user'), name='unique_round_submission_judge_assignment'),
        ),
        migrations.AddIndex(
            model_name='judgeinvitation',
            index=models.Index(fields=['round'], name='judging_jud_round_i_8c466c_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeinvitation',
            index=models.Index(fields=['email'], name='judging_jud_email_3c914a_idx'),
        ),
        migrations.AddIndex(
            model_name='roundresult',
            index=models.Index(fields=['round', 'rank'], name='judging_rou_round_i_40efa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='roundresult',
            constraint=models.UniqueConstraint(fields=('round', 'submission'), name='unique_round_result_per_submission'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['submission', 'judge_user'], name='judging_sco_submiss_ec1e1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('submission', 'judge_user', 'criterion'), name='unique_score_per_submission_judge_criterion'),
        ),
    ]
