# Generated by Django 5.2.16 on 2026-07-22 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_opt_ins', to='submissions.submission')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_opt_ins', to='hackathons.challengetrack')),
            ],
            options={
                'db_table': 'submission_tracks',
                'indexes': [models.Index(fields=['track', 'submission'], name='subtrack_track_sub_idx')],
                'constraints': [models.UniqueConstraint(fields=('submission', 'track'), name='unique_submission_track')],
            },
        ),
    ]
