# Generated by Django 5.2.16 on 2026-07-17 11:24

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('banner_url', models.TextField(blank=True)),
                ('registration_opens_at', models.DateTimeField()),
                ('registration_closes_at', models.DateTimeField()),
                ('submission_opens_at', models.DateTimeField()),
                ('submission_closes_at', models.DateTimeField()),
                ('rules', models.TextField(blank=True)),
                ('prize_info', models.TextField(blank=True)),
                ('location_mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('eligibility_rules', models.JSONField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('showcase_published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hackathons_created', to=settings.AUTH_USER_MODEL)),
                ('host_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hackathons', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prize', models.TextField(blank=True)),
                ('rubric_reference', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_tracks', to='organizations.organization')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='hackathons.hackathon')),
            ],
        ),
        migrations.AddIndex(
            model_name='hackathon',
            index=models.Index(fields=['status', 'registration_opens_at'], name='hackathon_status_regopen_idx'),
        ),
        migrations.AddIndex(
            model_name='hackathon',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='hackathon_tags_gin_idx'),
        ),
        migrations.AddConstraint(
            model_name='hackathon',
            constraint=models.CheckConstraint(condition=models.Q(('registration_closes_at__gt', models.F('registration_opens_at'))), name='hackathon_registration_close_after_open'),
        ),
        migrations.AddConstraint(
            model_name='hackathon',
            constraint=models.CheckConstraint(condition=models.Q(('submission_closes_at__gt', models.F('submission_opens_at'))), name='hackathon_submission_close_after_open'),
        ),
        migrations.AddIndex(
            model_name='challengetrack',
            index=models.Index(fields=['hackathon'], name='hackathons__hackath_e00db4_idx'),
        ),
        migrations.AddIndex(
            model_name='challengetrack',
            index=models.Index(fields=['sponsor_org'], name='hackathons__sponsor_2d197e_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengetrack',
            constraint=models.UniqueConstraint(fields=('hackathon', 'name'), name='unique_track_name_per_hackathon'),
        ),
    ]
