# Generated by Django 5.2.16 on 2026-07-24 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
        ('organizations', '0002_organization_is_suspended_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='hackathon',
            index=models.Index(fields=['is_suspended'], name='hackathon_is_suspended_idx'),
        ),
    ]
