# Generated by Django 5.2.17 on 2026-09-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_hackathon_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='prize_distribution',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='total_prize_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
