# Generated by Django 5.2.17 on 2026-09-01 14:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_hackathon_prize_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='field',
            field=models.CharField(blank=True, default='Technology', max_length=100),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='open_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
