# Generated by Django 5.2.17 on 2026-09-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='knowledge_b_status_080244_idx',
            old_name='knowledge_b_status_2b291f_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='knowledge_b_slug_c37eab_idx',
            old_name='knowledge_b_slug_ddcc80_idx',
        ),
    ]
