# Generated by Django 5.2.17 on 2026-09-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('looking_for_team', 'Looking for a Team'), ('create_team', 'Create a Team')], default='solo', max_length=20),
        ),
    ]
