# Generated by Django 5.2.17 on 2026-09-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='support_ai__user_id_aa5c63_idx',
            old_name='support_ai__user_id_01de49_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='support_ai__source__9b430f_idx',
            old_name='support_ai__source__2cefa4_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='support_ai__visibil_99c7b7_idx',
            old_name='support_ai__visibil_e49a8d_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='support_ai__hackath_0761e3_idx',
            old_name='support_ai__hackath_a1fbbd_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='support_ai__organiz_929756_idx',
            old_name='support_ai__organiz_a70cc4_idx',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
