# Generated by Django 5.2.17 on 2026-09-10 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='internalnote',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='support_ass_ticket__45ea29_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='support_ass_assigne_7530d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='attachment',
            name='support_att_ticket__5d23cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='internalnote',
            name='support_int_ticket__c94bf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='statushistory',
            name='support_sta_ticket__cd6f54_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketmessage',
            name='support_tic_ticket__8d6bd5_idx',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_notes_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_status_changes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('billing', 'Billing'), ('general', 'General'), ('hackathon_specific', 'Hackathon Specific')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='scope_type',
            field=models.CharField(blank=True, choices=[('hackathon', 'Hackathon'), ('organization', 'Organization')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['ticket', 'unassigned_at'], name='support_ass_ticket__8cf667_idx'),
        ),
        migrations.AddIndex(
            model_name='internalnote',
            index=models.Index(fields=['ticket'], name='support_int_ticket__cffe1a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket'], name='support_tic_ticket__318600_idx'),
        ),
    ]
