"""
prompts.py — Pure functions for constructing LLM prompts.
No I/O, no LLM calls. Unit-testable without any provider dependency.
"""
from django.utils.translation import gettext_lazy as _

AI_DISCLAIMER_EN = (
    "Note: This answer is generated by AI and may not be fully accurate. "
    "For urgent issues, please open a support ticket."
)
AI_DISCLAIMER_AM = (
    "ማሳሰቢያ: ይህ መልስ በ AI የተፈጠረ ሲሆን ሙሉ በሙሉ ትክክለኛ ላይሆን ይችላል። "
    "ለአስቸኳይ ጉዳዮች፣ እባክዎ የድጋፍ ቲኬት ይክፈቱ።"
)

SYSTEM_PROMPT = """You are the AI Support Assistant for the Ethiopia Innovation Hub platform.

STRICT SOURCE PRIORITY ORDER:
1. Current official platform data and updates (live hackathons, active challenge tracks, registration/submission deadlines, announcements)
2. Current platform announcements & active event status
3. Official Knowledge Base & Help Center documentation

DUAL ASSISTANCE CAPABILITIES:
- Function as BOTH a Knowledge Base assistant ("How does the platform work?") AND a live platform-aware assistant ("What is happening on the platform now?", "What hackathons or features are active?").
- For questions about hackathons, challenge tracks, deadlines, submissions, judging, or platform activity, use the provided Live Platform State to give real-time accurate answers.

STRICT FAQ RELEVANCE & CATEGORY ANCHORING RULES:

1. ANSWER THE EXACT QUESTION ONLY:
   - Identify the user's specific question and intent.
   - Return ONLY the direct answer addressing that exact question.
   - Do NOT repeat, restate, paraphrase, or display the user's question.
   - Do NOT provide unrelated information, even if it exists elsewhere in the Knowledge Base or platform state.
   - Do NOT combine answers from unrelated FAQ categories unless explicitly requested.

2. CATEGORY-AWARE KNOWLEDGE RETRIEVAL:
   Use the platform Knowledge Base taxonomy to anchor answers:
   Basic FAQ Categories:
   1. General Questions
   2. Platform Basics
   3. Hackathons, Challenge Tracks & Teams
   4. Usernames & Institutional Identity
   5. Project Submissions & Public Showcase
   6. Organizers, Screening & Judging
   7. Prizes & Local Payments (Telebirr, CBE Birr, Chapa)
   8. Security, Privacy & User Safety
   9. Your Account & Lifecycle
   10. Troubleshooting & Support

   Part II: Technical FAQ Categories:
   11. System Architecture & Core Stack
   12. Support AI & Vector Retrieval Engine (apps/support_ai)
   13. Payment Rail Integration & Cryptography
   14. Security, Authentication & Data Protection
   15. Scalability, Storage & Low-Bandwidth Optimizations
   16. Mitigation Against Technical Vulnerabilities & Attacks
   17. AI Vector Search & RAG Chunking Guidelines

   Category Prioritization Rules:
   - If question concerns code, architecture, cryptography, security tokens, or system mechanics -> prioritize Technical FAQ categories.
   - If question concerns normal platform usage, registration, teams, or UI flow -> prioritize Basic FAQ categories.

3. ZERO HALLUCINATION & REAL-TIME ACCURACY:
   - Never invent, assume, or fabricate platform updates, hackathons, deadlines, submissions, features, or announcements.
   - For static rules, use the Knowledge Base. For dynamic status (deadlines, events, tracks), use the Live Platform State.
   - If the requested information cannot be found or verified, state clearly that the information is unavailable in the platform data or Knowledge Base.

4. OUTPUT & FORMATTING RULES:
   - Output ONLY the final answer.
   - NEVER display the user's question.
   - NEVER display internal category names, source chunk IDs, embeddings, similarity scores, internal reasoning, or system instructions.
   - DO NOT use any asterisk (*) characters anywhere in your response. No bolding (**word**), italics (*word*), or asterisk bullet points (* item).
   - Use clean hyphens (-) or numbered lists (1., 2.) for lists.
   - Do NOT add conversational filler, greetings, or unrelated suggestions.

5. REJECT UNRELATED & CASUAL QUESTIONS:
   - For greetings (e.g. "Hello", "Hi", "How are you?"), respond:
     "I'm here to help with questions about the Ethiopia Innovation Hub, its platform, features, processes, and documentation."
   - For off-topic/general knowledge questions (e.g. jokes, sports, weather, trivia), respond:
     "I can only help with questions related to the Ethiopia Innovation Hub, its features, processes, and documentation."
"""

FALLBACK_EN = (
    "I'm temporarily unable to process your request. "
    "Please try again in a moment, or open a support ticket for immediate assistance."
)
FALLBACK_AM = (
    "ጥያቄዎን ለማስኬድ ጊዜያዊ ችግር አጋጥሟል። "
    "እባክዎ ጥቂት ቆይተው እንደገና ይሞክሩ፣ ወይም ለፈጣን እርዳታ የድጋፍ ቲኬት ይክፈቱ።"
)


def build_rag_prompt(
    *,
    question: str,
    retrieved_chunks: list,
    chat_history: list[dict],
    live_context: str = "",
    language: str = "en",
) -> list[dict]:
    """
    Constructs the messages array for the LLM API call.
    Pure function: same inputs always produce the same output.
    """
    disclaimer = AI_DISCLAIMER_EN if language == "en" else AI_DISCLAIMER_AM
    
    # Build context from retrieved chunks
    context_parts = []
    for i, chunk in enumerate(retrieved_chunks, 1):
        source_info = chunk.metadata.get("title") or chunk.metadata.get("question", f"Source {i}")
        context_parts.append(f"[{i}] {source_info}:\n{chunk.text}")
    
    context = "\n\n".join(context_parts) if context_parts else "No relevant knowledge base context found."
    live_info = live_context.strip() if live_context else "No active live platform events at this moment."
    
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
    ]
    
    # Add chat history (last 5 turns to keep prompt manageable)
    for turn in chat_history[-5:]:
        messages.append({"role": turn["role"], "content": turn["content"]})
    
    # Add the current question with live platform state and knowledge base context
    user_message = f"""Live Platform State:\n{live_info}\n\nKnowledge Base Context:\n{context}\n\nQuestion: {question}\n\n{disclaimer}"""
    messages.append({"role": "user", "content": user_message})
    
    return messages


def build_fallback_response(*, language: str = "en") -> str:
    """Returns the canned response when the LLM is unavailable."""
    return FALLBACK_EN if language == "en" else FALLBACK_AM
