# Generated by Django 5.2.16 on 2026-07-23 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0001_initial'),
        ('submissions', '0002_submissiontrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField()),
                ('reason', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showcase_overrides_made', to=settings.AUTH_USER_MODEL)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_overrides', to='hackathons.hackathon')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_override', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['hackathon'], name='showcase_sh_hackath_32fae5_idx')],
            },
        ),
    ]
