# Generated by Django 5.2.16 on 2026-07-24 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_suspended'], name='organizatio_is_susp_c6c357_idx'),
        ),
    ]
