# Generated by Django 5.2.16 on 2026-08-04 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_is_suspended_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain_fast_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['domain_fast_tracked'], name='organizatio_domain__57cd82_idx'),
        ),
    ]
