# Generated by Django 5.2.17 on 2026-09-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_domain_fast_tracked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
    ]
